name: Download and Merge Tiles

on:
  workflow_dispatch
  
jobs:
  download-and-merge:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tomsk
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        sparse-checkout: |
          requirements.txt
          download_and_merge_tiles.py
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        echo "Installing dependencies with pip cache..."
        pip install --cache-dir ~/.cache/pip -r requirements.txt
        echo "Pip cache location: $(pip cache dir)"
        echo "Pip cache info: $(pip cache info)"
        
    - name: Create output directory
      run: mkdir -p output
      
    - name: Download and merge tiles
      run: python download_and_merge_tiles.py

